### ISSUE TITLE
我的训练结果和您的有很大不同。请问和python版本有关吗

### ISSUE THREAD

**Issue by chde222** [vinay0410/Pedestrian_Detection#4]
您好，谢谢您的readme。写的很仔细，很棒。
但是我利用python3版本，scikit-image是0.15.0和scikit-learn是0.21.3.训练完成后运行结果和前面提出问题的那位朋友一样，我该怎么解决呢？是数据集的问题吗？因为我在下载Person数据集解压时有一些出现错误。求解答

**Comment by vinay0410** [comment]
**Translated Version:**
Hi, thank you for your readme. It was written very carefully and it was great.
But I use python3 version, scikit-image is 0.15.0 and scikit-learn is 0.21.3. After training, the running result is the same as the friend who asked the question before. How can I solve it? Is it a data set problem? Because I got some errors when I downloaded the Person dataset and decompressed it. Ask for an answer

**Comment by vinay0410** [comment]
Hi @chde222 , [INRIA Dataset](http://pascal.inrialpes.fr/data/human/) contains some old/broken png images. To fix that I have written a script called `fixpng.sh`, which can be found in the repository.
Did you run this script ?

Also, to run this script you must have `pngfix` installed.

**Comment by chde222** [comment]
ok I will try soon

**Comment by chde222** [comment]
its so terrible but where may be the problem?
![hogterrible](https://user-images.githubusercontent.com/45227620/71083307-ad6f8280-21cd-11ea-8f4e-902fadfef4ca.png)

**Comment by vinay0410** [comment]
Could you please post the results for the images mentioned in readme. So that it’s better to compare.

**Comment by vinay0410** [comment]
@chde222 , this is a simple detector based on svm and hog, if you need more powerful detectors, checkout the following repo.
[https://github.com/JdeRobot/DetectionStudio](https://github.com/JdeRobot/DetectionStudio)
