### ISSUE TITLE
It detects and creates window even when there is  no human.

### ISSUE THREAD

**Issue by NarasimhaD01** [vinay0410/Pedestrian_Detection#9]
Hello Vinay,

I was running the detection.py to run and see if it detects only human.
I could see when I run detection.py over negative images, still it detects some feature where there is no human.

For the following command:
python detectmulti.py -i INRIAPerson/test_64x128_H96/neg/no_person__no_bike_173.png
(480, 640)
(576, 352)
(array([1]), 120, 112)
1
(320, 426)
(362, 192)
2
(213, 284)
(220, 85)
3
(142, 189)
(125, 14)
4
(94, 126)
(62, -34)
5
[(112, 120, array([0.35029533]), 64, 128)]

I am getting before and after Nms as  : 
![Before NMS](https://user-images.githubusercontent.com/70700669/95059416-24442080-06f9-11eb-95b2-ea4b053cbaf7.png)
![After NMS](https://user-images.githubusercontent.com/70700669/95059420-260de400-06f9-11eb-95b1-99b727bf21e6.png)

Could you please confirm, for negative test, shall there be detection ?

Also, could you let me know how can I get accuracy for a single image while testing ?

One more instance:
python detectmulti.py -i INRIAPerson/Train/neg/no_person__no_bike_262.png
(480, 640)
(576, 352)
(array([1]), 280, 0)
1
(320, 426)
(362, 192)
2
(213, 284)
(220, 85)
(array([1]), 72, 72)
3
(142, 189)
(125, 14)
4
(94, 126)
(62, -34)
5
[(0, 280, array([0.44814021]), 64, 128), (162, 162, array([0.14749357]), 144, 288)]

![After NMS_1](https://user-images.githubusercontent.com/70700669/95060049-0a570d80-06fa-11eb-9068-56830b7b6ebc.png)

**Comment by vinay0410** [comment]
There can be false positives always.
Although, it could also be because of some issues in training.
I would suggest running detection using the pre trained model in the repo, and see if you get same results.

FYI, if you need to something state of the art, try CNN, as already suggested previously.

Try the following repository, it has far better accuracy in detecting humans.

github.com/JdeRobot/DetectionStudio
